### PR TITLE
Move design style tweaks

### PR DESCRIPTION
**Pull request by thomasleese**
This makes a few changes to the new move pages following further design refinements. See individual commits for more details.

## Old

Screenshot 2021-09-13 at 10 30 49

Screenshot 2021-09-10 at 13 33 30

Screenshot 2021-09-13 at 10 17 38

## New

Screenshot 2021-09-13 at 10 31 03

Screenshot 2021-09-10 at 13 33 47

Screenshot 2021-09-13 at 10 17 25

[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3133)

### CODE REVIEW

**Review by Thource — APPROVED** [review]

**Comment by ElizabethGoddard** [comment]
Hey @thomasleese thank you for this!

1. The opt-in banner looks perfect

2. For the text change 'started' we only want to change the copy in the moves pages warnings tab before the PER has been started. I think you may have changed it in the listing screen also - but in that case alerts don't show until the PER is completed so the change is not required. Does that make sense? For reference we have the following states (I think!):

a) Warnings tab before PER started = Nothing shows until PER is started 
b) Warnings tab 'Overview' section = Nothing shows until PER is completed 
c) Warnings tab PER sections = Nothing shows until relevant section is completed 
d) Listing screen = Nothing shows until PER is completed.

3. Looking at your screenshots has made me realise we should match the style in the 'Person to be added' component with the reference at the end i.e. Person to be added (TNV9734U) for consistency. However I had not put this on the original ticket. Do you think it makes sense to fix that here or start a new ticket for it?

Any questions shout. Thank you!

**Comment by thomasleese** [comment]
@ElizabethGoddard 

> 2. For the text change 'started' we only want to change the copy in the moves pages warnings tab before the PER has been started. I think you may have changed it in the listing screen also - but in that case alerts don't show until the PER is completed so the change is not required. Does that make sense? For reference we have the following states (I think!):

Ah yes, the text is actually referenced in both places, so changing it one place changes it in the other. I had assumed changing it both places was right, but I can split the reference so it's as you say!

> 3. Looking at your screenshots has made me realise we should match the style in the 'Person to be added' component with the reference at the end i.e. Person to be added (TNV9734U) for consistency. However I had not put this on the original ticket. Do you think it makes sense to fix that here or start a new ticket for it?

Yeah, I spotted this too when I was working on it. I'd suggest we raise it as a new ticket because I don't think this change makes it any worse. What do you think?

**Comment by ElizabethGoddard** [comment]
Sounds great @thomasleese I'll create a new ticket for that yeah makes sense. Drop me a note when you've made that other change and then I'll approve the PR. Thanks!

**Comment by thomasleese** [comment]
> Sounds great @thomasleese I'll create a new ticket for that yeah makes sense. Drop me a note when you've made that other change and then I'll approve the PR. Thanks!

That's sorted now, I haven't changed the screenshot above (so it's showing the wrong phrasing now) but let me know if you'd like me to do that!

**Comment by ElizabethGoddard** [comment]
> > Sounds great @thomasleese I'll create a new ticket for that yeah makes sense. Drop me a note when you've made that other change and then I'll approve the PR. Thanks!
> 
> That's sorted now, I haven't changed the screenshot above (so it's showing the wrong phrasing now) but let me know if you'd like me to do that!

Thank you! Will you be deploying it to staging?

**Comment by ElizabethGoddard** [comment]
@thomasleese yeah maybe update the screenshot if you don't mind, just incase I revisit this PR I might get confused :)

**Comment by thomasleese** [comment]
> Thank you! Will you be deploying it to staging?

Yeah, once merged it will go to staging automatically, it should also be visible in the Heroku previews too.

**Comment by ElizabethGoddard** [comment]
@thomasleese Sorry yeah I meant Heroku, I don't see it yet but once it's gone through I'll take look. Thank you!

**Comment by thomasleese** [comment]
> @thomasleese Sorry yeah I meant Heroku, I don't see it yet but once it's gone through I'll take look. Thank you!

Cool, the deployment should be working now :)

**Review by ElizabethGoddard — APPROVED** [review]
Perfect thank you!

**Pull request merged**
